### ISSUE TITLE
Consider adding the deploy key to ssh-agent

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/dpl#1052]
https://github.com/travis-ci/dpl/pull/1031#discussion_r313927540

We currently store the per-job ssh key (e.g. Heroku), as well as a GitHub deploy key if given (e.g. Pages) to the disk, and then setup `git_ssh` to use it: https://github.com/travis-ci/dpl/blob/master/lib/dpl/assets/dpl/git_ssh

An alternative strategy would be to add the key to the ssh agent, e.g.

```
ssh-agent '
  echo $ssh_key_var | ssh-add -
  ssh -T git@github.com  # check auth
  git ...
'
```

This would have the advantage that we don't leave these files on the disk, e.g. in cases where `dpl` is being used locally.

We could then also remove the key from the agent in the `before_finish` stage as we do that with keys pushed to the respective service provider https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider.rb#L294 (If we have written a key to `~/.dpl/*` we currently just leave it there.)

**Comment by webknjaz** [comment]
Removing the key from an agent isn't necessary: if you run it as in the example, it's being autoremoved because `ssh-agent` gets terminated after it finishes the script in the argument.
Another strategy would be spawning a completely separate ssh-agent instance before hitting SSH, then pre-populating SSH invocation with env vars pointing to this brand-new agent instance and finally killing it once it's not needed anymore. This has the advantage of having only the necessary key loaded in memory which prevents SSH from iterating over wrong keys which sometimes leads to "invalid login" response because of reaching server auth attempt limits.

**Comment by webknjaz** [comment]
unstale

**Comment by webknjaz** [comment]
Here's an ssh-agent GitHub Action for inspiration: https://github.com/webfactory/ssh-agent

**Comment by webknjaz** [comment]
unstale

**Comment by webknjaz** [comment]
unstale
