### ISSUE TITLE
Correct ZIP upload for Java lambda

### ISSUE THREAD

**Issue by pat-lego** [travis-ci/dpl#1077]
The Lambda file that is uploaded is corrupt and it does not run on AWS Lambda. After using the new dpl v2 the uploaded artifact does not run. Using the amazon cli works fine.

I believe the issue is the way that the stream is being sent to the AWS lambda function.

https://github.com/travis-ci/dpl/blob/af2aac2db85676797478b8b7e01638e50720c39b/lib/dpl/helper/zip.rb#L14

This requires some investigation.

**Comment by svenfuchs** [comment]
Hmmmm, that's strange. 

A few observations:

* In v1 we've also passed a `File` instance: https://github.com/travis-ci/dpl/blob/v1/lib/dpl/provider/lambda.rb#L131. However, that didn't call `open`, but just `new`
* The [AWS docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Lambda/Client.html#update_function_code-instance_method) say "zip_file (String, IO) — The base64-encoded contents of the deployment package. AWS SDK and AWS CLI clients handle the encoding for you.", and the example given is `zip_file: "fileb://file-path/file.zip` ... so that sounds we could just pass the path to the zip.
* This integration test happily uploads a zip file, albeit a very small one: https://travis-ci.com/travis-ci/dpl/builds/124131260#L184 (config is [here](https://github.com/travis-ci/dpl/blob/master/.travis/providers/aws-lambda/travis.yml#L27), the zip is created [here](https://github.com/travis-ci/dpl/blob/master/.travis/providers/aws-lambda/prepare#L18))

We don't actually know if it's an issue with your zip created on Travis CI, do we? Have you ever successfully uploaded the same zip file from Travis CI (e.g. using a debug build)?

I am going to try running an integration test against a branch that removes `File.open` and just passes the path as a string.

**Comment by svenfuchs** [comment]
i just noticed there's another comment on https://github.com/travis-ci/dpl/pull/1027#issuecomment-523620241 ... but looking at the timestamps you seem to have opened this issue about 15min later.

So AWS has accepted the upload request and reported it to be successful, but then it turned out to be corrupt?

**Comment by pat-lego** [comment]
@svenfuchs Yes it sounds really weird but I uploaded the zip with the deployment using master and then I ran my function and it just failed. I need to look at the Cloud Watch logs to see what is happening but my only logical consensus is that somehow the zip is corrupt. I would need to do further investigation on my side.

**Comment by svenfuchs** [comment]
aaah, ok. i guess i misunderstood.

in the meantime i have run a test passing the path to the zip file as a plain string, as well as a `File` instance (using `File.new`), and both worked just fine. it seems the SDK doesn't seem to care about these (which i think would make sense).

* https://travis-ci.com/travis-ci/dpl/builds/124133842
* https://travis-ci.com/travis-ci/dpl/builds/124133779

i'll probably change master to pass the plain string for now, seems a little cleaner to me.

i'll wait what you come with otherwise.

**Comment by pat-lego** [comment]
@svenfuchs I ran some tests and the DPL library deploys fine it's due to the fact that the Lambda function takes more than a few seconds to execute and for that reason it fails. I simply added the timeout and memory_size options to the deployment function and it deployed perfectly fine. We can close this issue.

**Comment by svenfuchs** [comment]
@pat-lego that's great to hear, glad it's now working for you!

thanks for letting me know. i'm going to close the issue then.
