### ISSUE TITLE
Invalid option [provider]

### ISSUE THREAD

**Issue by melvyn2** [travis-ci/dpl#1099]
Any provider is an invalid option:
```
root@37310d0ca4b0:/# gem install dpl dpl-releases
[...]
Done installing documentation for multipart-post, faraday, public_suffix, addressable, sawyer, octokit, mime-types-data, mime-types, dpl-releases after 5 seconds
10 gems installed
root@37310d0ca4b0:/# dpl
Installing deploy dependencies
missing provider
root@37310d0ca4b0:/# dpl releases
invalid option "releases"
root@37310d0ca4b0:/# dpl gcs
invalid option "gcs"
```
If I'm missing any logs or other files, I'd be glad to upload them.

**Comment by svenfuchs** [comment]
@melvyn2 where have you found the instruction to run `gem install dpl dpl-releases`, and which documentation are you referring to?

`dpl-releases` is a sub gem of dpl `v1`, which still is the currently released stable version. i don't think this version has ever accepted `dpl gcs`

the current `master` branch contains `v2` which is released as a preview release, so you'll want to install it using `gem install dpl --pre` (no `dpl-releases`).

i have updated the readme to mention this https://github.com/travis-ci/dpl#installation.

i'll close this issue here. please feel free to reopen if needed.

**Comment by melvyn2** [comment]
Sorry about that - I hadn't thought about version differences. As expected, the prereleases follow documented behavior.

**Comment by svenfuchs** [comment]
@melvyn2 no worries. thanks for the report anyway!
