### ISSUE TITLE
"Install deployment dependencies" fails on Windows

### ISSUE THREAD

**Issue by annulen** [travis-ci/dpl#1107]
In the build https://travis-ci.org/qtwebkit/release-tests/builds/589058861 there are 2 jobs which use the same deployment configuration. On Linux everything is fine, while on Windows it fails with

```
ruby -S gem uninstall -aIx dpl
/c/Users/travis/.travis/functions: line 553:  4656 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
Gem 'dpl' is not installed
$ ruby -S gem install dpl --pre
Successfully installed regstry-1.0.14
Successfully installed cl-1.1.5
Successfully installed dpl-2.0.0.alpha.6
Parsing documentation for regstry-1.0.14
Installing ri documentation for regstry-1.0.14
Parsing documentation for cl-1.1.5
Installing ri documentation for cl-1.1.5
Parsing documentation for dpl-2.0.0.alpha.6
Installing ri documentation for dpl-2.0.0.alpha.6
Done installing documentation for regstry, cl, dpl after 2 seconds
3 gems installed

Install deployment dependencies
Installing deployment dependencies

failed to deploy
Support for deployments to Bintray is in **alpha**. Please see [Maturity Levels](https://github.com/travis-ci/dpl/#maturity-levels) for details.
cannot load such file -- bundler/inline (LoadError)
```
See full log at https://travis-ci.org/qtwebkit/release-tests/jobs/589058865
Error reproduces if job is restarted.

**Comment by annulen** [comment]
Any ideas?

**Comment by cesar-cs** [comment]
Apparently Chocolatey does not have a standalone Bundler package so I believe the best way to install bundler is by using gem.

**Comment by annulen** [comment]
It worked, thanks!

**Comment by annulen** [comment]
Actually, it doesn't work correctly. In the build at https://travis-ci.org/qtwebkit/release-tests/jobs/590680229 file `qa-142.4-windows.7z` is not uploaded correctly (https://bintray.com/beta/#/qtproject/qtwebkit-qa/qa/142?tab=files) - seems like only beginning of file is uploaded. On Linux corresponding file is uploaded correctly.

**Comment by svenfuchs** [comment]
@annulen great to hear you've made progress on this one.

looking at your build log i don't think the truncated file can be an issue on our side anymore though. Bintray has reported a `201` on the uploading POST request https://travis-ci.org/qtwebkit/release-tests/jobs/590680229#L1657

this is using Ruby's `net/http` standard library, and runs these requests in a synchronous fashion. i don't see any potential for that problem being on our side, unless there's a general problem with `net/http` on Windows (which i can't think there is).

i think it might make sense to turn to Bintray's support and ask if this is a know issue. also, it might make sense to run this a couple times to see if it's consistent.

i'm going to close the issue here for now. please feel free to reopen it if needed.

**Comment by annulen** [comment]
Will you fix automatic installation of bundler? When using declarative settings in .travis.yml, it comes really unexpected that additional gems need to be explicitly installed to make it working.

As for file trucation, it's reproducible and happens only on Windows, so I'm pretty sure that problem is not on Bintray side

**Comment by annulen** [comment]
I've used curl command in after_deploy to upload file to Bintray, and now it's working correctly
