### ISSUE TITLE
Allow override of `npm publish`

### ISSUE THREAD

**Issue by kripod** [travis-ci/dpl#1118]
When publishing packages of a monorepo, a custom npm script needs to be used (e.g. `npm run publish`, which would execute `lerna publish from-package --contents pkg` or similar, see [the corresponding issue](https://github.com/pikapkg/pack/issues/1) of pikapkg/pack).

I think that if a `publish` script is present in `package.json`, it should be preferred over the default publishing method.

**Comment by svenfuchs** [comment]
@kripod thanks for opening this!

is our understanding correct that you'd like `dpl npm` use `npm run publish` rather than `npm publish` automatically if the `package.json` contains a `publish` script?

if we did so we are concerned that we'd do so for users who do not want that, so our thinking is that we'd want an additional opt-in option, e.g. `--run_script` (or similar).

how common is it to define a `publish` script in the `package.json` file?

**Comment by kripod** [comment]
> is our understanding correct that you'd like `dpl npm` use `npm run publish` rather than `npm publish` automatically if the `package.json` contains a `publish` script?

Yeah, I proposed it exactly as you've described.

> if we did so we are concerned that we'd do so for users who do not want that, so our thinking is that we'd want an additional opt-in option, e.g. `--run_script` (or similar).

An opt-in feature would be very sensitive, great idea indeed.

> how common is it to define a `publish` script in the `package.json` file?

I'm not sure about it, but it's a viable use-case [for monorepos](https://github.com/lerna/lerna/tree/master/commands/publish#readme).

**Comment by svenfuchs** [comment]
@kripod i have added https://github.com/travis-ci/dpl/pull/1124 which i believe should address this.

could you give it a run?

```yaml
deploy:
- provider: npm
  edge: 
    branch: sf-run_script
```

**Comment by kripod** [comment]
It [works flawlessly](https://www.travis-ci.com/kripod/react-hooks/jobs/249181556), thank you once again!
