### ISSUE TITLE
Key 'cleanup: false' not working even if suggested in config validation

### ISSUE THREAD

**Issue by fcole90** [travis-ci/dpl#1174]
When running a job, I used the key  `skip_cleanup: true` . When checking the config validation I got a suggestion to change it to be  `cleanup: false` , as  `skip_cleanup`  was going to be deprecated. However, using the new key doesn't seem to have any effect and the environment gets git stashed.

**What happened** :
I got suggestion to use  `cleanup: false`  to avoid a cleanup but it did not work.

![image](https://user-images.githubusercontent.com/1292230/75621721-a935ed00-5ba0-11ea-9d4e-76549777192a.png)

**What did I expect** :
Either not to receive the suggestion to change my keyword or that the suggested keyword worked as expected.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by fcole90** [comment]
I get it. Yes, that's a private repo for the moment. Thanks for letting me know :blush:

**Comment by svenfuchs** [comment]
@fcole90 thanks for the report. i agree the message is confusing in this particular context. 

the option `cleanup: true` is present in the version `v2` of the deployment tooling `dpl` as mentioned in the message. 

in order to switch to `v2` and get rid of the message you can set:

```yaml
deploy:
- provider: ...
   edge: true
```

alternatively, you can ignore the message until this becomes the default version.

we recommend switching though, in order to make certain your deployments continue to run smoothly.

**Comment by fcole90** [comment]
Thanks, @svenfuchs. I had undestood it as being already available in the current dpl. Thanks for clarifying, I'll try the new version as you suggest :blush:
