### ISSUE TITLE
Problems with GitHub deploy updating Release body

### ISSUE THREAD

**Issue by PhilMFischer** [travis-ci/dpl#1203]
There seems to be an issue with updating the Release body message.

We have the following case:

Our build under https://travis-ci.com/github/virtualsatellite/VirtualSatellite4-DEV-IDE/builds/175412233 is running an integration build. It is setting the `integration_snapshot` tag always to the latest commit on the `integration` branch. Once the build is succesful some files are uplaoded to the integration Release https://github.com/virtualsatellite/VirtualSatellite4-DEV-IDE/releases . The body of the release message should be updated with the time and commit sha of the build. 

This used to work fine and stopped meanwhile. Today it seems the release message is not getting changed at all when deploying.

**Comment by PhilMFischer** [comment]
Additional Info. Judging from our build history, It seems that the feature was working at least until 14. January 2020

**Comment by Velenir** [comment]
Have the same issue
[Body](https://github.com/gnosis/dex-react/blob/v0.5.1/.travis.yml#L68) stopped being filled somewhere between [Jan 7](https://github.com/gnosis/dex-react/releases/tag/v0.5.0) and [Jan 27](https://github.com/gnosis/dex-react/releases/tag/v0.5.1)

Tried out using `release_notes` instead of `body`, to no avail.
On the other hand, [`file`](https://github.com/gnosis/dex-react/blob/v1.1.2/.travis.yml#L76) gets posted to releases without problem

**Comment by anxolin** [comment]
Same here! `body` stopped working without us doing any changes in the travis script

**Comment by BanzaiMan** [comment]
Sorry for the delayed response.

I've tracked this down to the introduction of configuration validator.

While we work on the fix, one workaround is to disable it in https://travis-ci.org/OWNER/REPO/settings, in the "Beta features" section at the bottom of the page.

We'll update this issue when the validator is fixed.

**Comment by BanzaiMan** [comment]
# Workarounds, so far

1. Stay with v1, disable configuration validation in https://travis-ci.org/OWNER/REPO/settings
1. Move to [v2](https://docs.travis-ci.com/user/deployment-v2) with `edge: true`. This should work whether or not configuration validation is enabled.
