### ISSUE TITLE
OpenShift only deploys master branch

### ISSUE THREAD

**Issue by koter84** [travis-ci/dpl#130]
when deploying different branches to a openshift target (with all_branches: true) travis should change the active/deployment branch of the openshift app before git push.
i found the command to switch which is:

```
rhc app-configure [app-name] --deployment-branch [branch]
```

as far as i understand this should go in `dpl/lib/dpl/provider/openshift.rb` in the `push_app` command but i'm unsure how to get the variables in the command.

also it seems that to push new branches the command
`git push #{app.git_url} -f`
should be changed to include the current branch name
`git push #{app.git_url} -f [branch]`

**Comment by pellenberger** [comment]
Hi ! 
I have several problems when deploying an app to openshift. This is related to this topic but there is something that I don't understand... 
I have a git repo with two branches : master and dev.
I want to deploy my two branches on two different openshift apps. 
My question : Is it enough to do this in my travis.yml file : 
  app:
    master: my-app
    dev: my-app-dev
With this expected behavior : push on master = deploy on my-app / push on dev = deploy on my-app-dev
Or have I to specify explicitly which branch I want to deploy with the deployment_branch parameter ?

Thank you for you answer !
