### ISSUE TITLE
Permissions errors during S3 deployment dependency installation

### ISSUE THREAD

**Issue by ChrisBeaumont** [travis-ci/dpl#175]
I've started hitting filesystem permissions errors during S3 deployment dependency installation.

Log file:
https://travis-ci.org/glue-viz/glue/jobs/35139976#L4219

.travis.yml file
https://github.com/glue-viz/glue/blob/9e4c3839818940fc78c25b2a2a0a2e1cf79c82c2/.travis.yml#L56

Any ideas what might be causing this?

Thanks,

**Comment by BanzaiMan** [comment]
Sorry for the (extremely) late reply. The reason that the deployment above failed was that for some reason `nokogiri` failed to install (https://travis-ci.org/glue-viz/glue/jobs/35139976#L4220) due to permission error. (I don't know why.)

We have updated S3 provider recently. If you still see the problem, please open a new issue.
