### ISSUE TITLE
Script provider fails silently if script cannot be found?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/dpl#333]
It seems the `script` provider fails without an error message if the given script cannot be found.

Looking at the implementation I am wondering if the condition `$?.exitstatus != 0` is evaluated at script compile time, while it should be checked at runtime? https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/script.rb#L19

/cc @BanzaiMan

**Comment by BanzaiMan** [comment]
It works for me. https://travis-ci.org/BanzaiMan/travis_production_test/builds/80421318#L120 (see the commit: https://github.com/BanzaiMan/travis_production_test/commit/21a37e40b70819fcfca4c745cc1811a8ac41725a)

dpl is an independent script from the build script, so `#exitstatus` does reflect the script executed.

**Comment by dandunckelman** [comment]
@BanzaiMan your test points to a valid file.  I think the issue occurs when referencing a file not found.  This specifically came about because I had a config like this:

```
script:
  - cd site/ta_apps/; bundle exec rake spec --trace
deploy:
  provider: script
  script: bin/deploy
  on:
    all_branches: true
```

The content of **bin/deploy** is this:
```
#!/bin/bash
set -ex

echo "TEST"
```

but it is never executed.  And **dpl** didn't tell me why it failed.

After telling @svenfuchs about my problem, he suggested I amend my script content to this:
```
script:
  - cd site/ta_apps/; bundle exec rake spec --trace; cd ../../
```

Once I did that, the build successfully ran the deploy script and showed the output of  **TEST**.  So, this seems to indicate that changing directories in the content of **script** was the root of the problem.  I know it's my fault that this failed, but I think it's reasonable to expect a message announcing that the file reference is no good.

**Comment by svenfuchs** [comment]
@dandunckelman I have tried to reproduce your issue here: https://github.com/svenfuchs/travis_production_test/blob/default/.travis.yml

Essentially:

```
deploy:
  provider: script
  script: ./does/not/exist
  on:
    all_branches: true
```

That should be the same case that you saw, right?

Curiously, this errors the build, and the error message is output to the log: https://travis-ci.org/svenfuchs/travis_production_test/builds/80471213

@BanzaiMan has any of this code changed just recently by any chance?

**Comment by dandunckelman** [comment]
@svenfuchs interesting.  The only difference is that mine had the script content changing directories before trying to reference the file.

Most likely, there haven't been any code changes, as both my failed builds and your successful build used dpl v1.8.2

**Comment by BanzaiMan** [comment]
Nothing changed recently. (https://github.com/travis-ci/dpl/commits/master/lib/dpl/provider/script.rb)

The issue is `cd`. When there is a discrepancy between the working directory and what the provider expects, it can be difficult to reconcile the difference in expectations.

If the user issues `cd` and expects to find the script relative to that directory, it would be wrong for the script provider to look for it from `$TRAVIS_BUILD_DIR`. On the other hand, it is not incorrect to expect that the script specified for the provider is always relative to `$TRAVIS_BUILD_DIR`.

In the end, I think we should give a more descriptive error message:

```ruby
      def push_app
        context.shell script
        if $?.exitstatus != 0
          raise Error, "Script #{File.join(ENV['PWD'], script)} failed with status #{$?.exitstatus}"
        end
      end
```

**Comment by dandunckelman** [comment]
Tidy. I like it.
