### ISSUE TITLE
support github pages

### ISSUE THREAD

**Issue by rkh** [travis-ci/dpl#34]

**Comment by jonnor** [comment]
Another reason for a deploy provider is to make use of the branch/repo filtering `on `, which one has to re-do manually if using something with git in `after_success`

**Comment by timwis** [comment]
Hey guys, I was looking to write a travis deployment provider for gh-pages since I use it so often and stumbled upon this thread. I've seen a lot of articles on the subject and I'm pretty confident that [this deployment script](https://github.com/timwis/static-api/blob/master/deploy.sh) used in the [deploy section](https://github.com/timwis/static-api/blob/master/.travis.yml#L12) of `.travis.yml` takes the best bits of each. (Note that I can't remember why I put a trailing `&& \` on each line...)

As @davidblurton mentioned above, a way to simply specify github pages as a provider in the `deploy` section and pass it the github token and the local build directory would be incredibly helpful.

I'm happy to put in the work if there's interest and someone can point me in the right direction.

**Comment by webknjaz** [comment]
Hey guys,

Could you plz check you my PR #501 implementing Github Pages deployment support.
I need some review, since normally I don't use Ruby.
TIA
