### ISSUE TITLE
GAE Java application with appengine-web.xml

### ISSUE THREAD

**Issue by Angelima** [travis-ci/dpl#389]
Hi, 
I'm curently trying to deploy a GAE app with your tool. But it's seems impossible because I have to provide an app.yaml file. 
But my app it's a simple Java GAE application with an application-web.xml. How can I specify the path file in the "config" attribut of deploy phase please.

The error stack trace : 

```
ERROR : File [src/main/webapp/WEB-INF/appengine-web.xml] is not a valid deployable yaml file.
```

**Comment by flowlo** [comment]
Hello!

As far as I know, deployment of Java Apps has always worked a bit differently than what the provider does. The provider works for the Apps using the `gcloud` tool, which is used with Python and Go Apps. It's my fault that the README does not talk about that specifically.

The ["Getting Started" tutorial suggests](https://cloud.google.com/appengine/docs/java/gettingstarted/uploading) to use a specific Maven plugin to upload Apps. There's more exhaustive docs on the plugin [here](
https://cloud.google.com/appengine/docs/java/tools/maven#uploading_your_app_to_production_app_engine).

So, I'd suggest setting up your project to use that plugin, and just execute `mvn appengine:update` as your deploy command.

As the deployment process for Java Apps is fundamentally different from the ones that leverage the Google Cloud SDK by invoking `gcloud`, a separate provider or a switch between two providers might make sense.

**Comment by JesseTG** [comment]
`mvn appengine:update` works around *this* issue, but exposes a brand new one; when deploying to Google App Engine, you're given a link with an authentication code that you're supposed to copy to the terminal.  You can't do that in Travis, so you're *still* stuck.  See [right down here](https://travis-ci.org/JesseTG/TicTacToe/jobs/108391840#L2504) for an example.

**Comment by flowlo** [comment]
@JesseTG I am on vacation and will check back on this in march.

**Comment by JesseTG** [comment]
OK, not a problem.  Enjoy yourself, then!

**Comment by lluft** [comment]
I guess something along those lines could be a viable solution: http://stackoverflow.com/questions/30332932/deploying-to-appengine-using-travis-ci-and-maven-without-oauth2

**Comment by JesseTG** [comment]
@flowlo Have you had a chance to look at this yet?

**Comment by flowlo** [comment]
I'm sorry to say that, but no, I did not look at it yet. The workaround @lluft referred to is quite ugly as well. 

I understand the need for a solution but I think that this will not be as straight forward. This is because using Maven to deploy is AFAIK recommended by Google as the de facto standard. So what I would have done would be to make the provider detect an `application-web.xml` and invoke `mvn` only to run into the issue you described.

It would be interesting to see whether one can use a Service Account to deploy with Maven. Also, it sounds probable that one could use the SDK and associated tools like `appcfg.sh` to generate `~/.appcfg_oauth2_tokens_java` by logging in using a Service Account. Of course I have not tested that ...

I implemented the App Engine provider in my free time, and unfortunately I have quite a lot of work to do currently (deadline on 2015-04-08), so sadly I cannot give any nice estimate on when I have time to analyze this. In the meantime feel free to investigate. If you come up with a nice solution I'd be more than happy to discuss it and aid integrating/merging it.

**Comment by JesseTG** [comment]
Running `mvn` is not the issue, the issue is having to navigate to a website to get a deployment code, then enter it manually.  Is there some `bash` + `curl` + `grep` magic or similar that I can do?

**Comment by flowlo** [comment]
@JesseTG Yep, you could attempt to do the following:

 1. `grep` the URL from the `mvn` output or whatever it is.
 2. `curl | grep` that URL looking for the `<title>` tag in the HTML
 3. Use what you extracted from the title as token.

Why the title you may ask... The HTML pages for this kind of authentication look like this

![](https://developers.google.com/accounts/images/installedresult.png)

(taken from [Google Developers](https://developers.google.com/identity/protocols/OAuth2InstalledApp#example)). As you can see, the code is displayed in the title bar. This is on purpose, because the title can be filtered more easily.

**Comment by JesseTG** [comment]
No way...I'll try this and get back to you on it, thanks!

**Comment by JesseTG** [comment]
Idea looks promising, but when trying `curl -L $(grep https://accounts.google.com "$THE_TRAVIS_OUTPUT" | tr -d [:space:])`, the resulting HTML is for the Google login page.  Is it possible for me to actually log in via `curl`?

**Comment by flowlo** [comment]
Oh crap, sorry I forgot that step. You'll have to grep for the submission URL of the form (or wherever the form redirects you).

**Comment by JesseTG** [comment]
The "URL" is just a `<input type="submit">`, I'm not sure if there's a URL to speak of (will let you know when I get home).

**Comment by flowlo** [comment]
An `<input type="submit">` in most cases is a child of a `<form action="$url">`. Look for that.

**Comment by JesseTG** [comment]
Ah, yes, I see it.  Still nothing, though; the main issue is being able to send in my password *and* the `<input type="hidden">`s (of which there are many).

**Comment by flowlo** [comment]
So we're back to finding a solution using `gcloud` I guess. Sorry for wasting your time, I hope you learned something new by trying things out :)

**Comment by JesseTG** [comment]
Yes, that when riding down shit creek a paddle is a luxury.  Thank you anyway.

**Comment by nickmoorman** [comment]
Hi folks.  I ran into this issue as well, and after a couple days of fumbling around, I figured out how to use a service account with the `mvn appengine:update` command.  The Maven plugin exposes many, but not all, of the commands supported by [`appcfg.sh`](https://cloud.google.com/appengine/docs/java/tools/appcfg-arguments).  However, I discovered that it will let you [configure](https://github.com/GoogleCloudPlatform/appengine-maven-plugin/blob/c4aae3259c651199eceb83695ae8d9a06919865f/src/main/java/com/google/appengine/appcfg/AbstractAppCfgMojo.java#L248) a list of [arbitrary params](https://github.com/GoogleCloudPlatform/appengine-maven-plugin/blob/c4aae3259c651199eceb83695ae8d9a06919865f/src/main/java/com/google/appengine/appcfg/AbstractAppCfgMojo.java#L380) that are eventually [passed to the same Java class](https://github.com/GoogleCloudPlatform/appengine-maven-plugin/blob/c4aae3259c651199eceb83695ae8d9a06919865f/src/main/java/com/google/appengine/appcfg/AbstractAppCfgMojo.java#L259).

So given that background, all you need to do to use a service account with `mvn appengine:update` is include something like this in the `appengine-maven-plugin` `<configuration>` block in your POM:
```xml
<additionalParams>
    <additionalParam>--service_account_json_key_file=path/to/service/account/key/file.json</additionalParam>
</additionalParams>
```

Hope this helps.

**Comment by MoriTanosuke** [comment]
This is still an issue for me, I don't have an `app.yml` but `appengine-web.xml`. I get the following errors at the end of my build:

````
ERROR    root            File [src/main/webapp/WEB-INF/appengine-web.xml] is not a valid deployable yaml file.
DEBUG    root            (gcloud.app.deploy) Errors occurred while parsing the App Engine app configuration.
````

Is there any way to deploy my java/maven project to GAE with Travis?

**Comment by alessandro-aglietti** [comment]
@MoriTanosuke thanks to @nickmoorman suggestions I was able to do push to deploy with Travis CI without using the pom.xml, I wont use the pom.xml because it's affect also the deployment from local IDEs.

Take a look of the .travis.yml here

https://github.com/growingabit/trt-tick-dumpster

BTW you need to set the Project Editor permission for the service account you use in Travis CI, take a look of the screenshoot in the README of the above project or read the "Primitive roles" here.

https://cloud.google.com/appengine/docs/standard/python/access-control
