### ISSUE TITLE
Google App Engine (gae) provider no longer supports free apps

### ISSUE THREAD

**Issue by erichiggins** [travis-ci/dpl#393]
It appears that the current version of the `gae` provider uses the `gcloud` commands, but these don't seem to support free apps running on App Engine. The change from `appcfg.py` to `gcloud` appeared to happen in [this commit](https://github.com/travis-ci/dpl/commit/f6d59f8bc2537631b5d9efdfb4910401d40147df) by @flowlo .You can see the logs from [a failed Travis build/deploy here](https://travis-ci.org/erichiggins/cmoanderic.com/builds/98849118).

Would it be possible to revive the previous version as an alternate provider to support free apps until gcloud is out of alpha? `gae_legacy`, perhaps?

**Comment by flowlo** [comment]
Hey!

First, to clarify: The changes I made were not meant to discriminate Apps using the free quota, and in fact I use the "new version" of the provider for Apps that only utilize free quota. So if your assumption turns out to be true (the provider can indeed only be used for paid apps) then this happened by accident, and I am very sorry for that.

Anyway, I would like to make sure that this is not an issue with your project setup. [Basically, `gcloud` says that the "default Google Cloud Storage bucket" for your App could not be found](https://travis-ci.org/erichiggins/cmoanderic.com/builds/98849118#L218). This could have other root causes than a malfunctioning provider. For example, I found [this hint](https://cloud.google.com/appengine/docs/python/googlecloudstorageclient/activate#Using_the_Default_Bucket) that says that the default bucket might not be there for Apps created with the "new" Cloud Platform Console. So in case you created the project recently (your GitHub repository looks quite young), this might be the cause. Could you please check? Just navigate to the Google Storage section inside the Cloud Platform Console, and verify that the bucket(s) are there. One should be named `cmoanderic.appspot.com`.

If this does not resolve the issue, please verify that you can deploy the App manually from your workstation using the `gcloud` tool and friends. The command should look like

```
$ gcloud --rpoejct="cmoanderic" preview app deploy --version="master-0x2x5" \
    --no-promote app.yaml
```

Thanks!

**Comment by erichiggins** [comment]
Thanks for the detailed follow-up @flowlo 

The first instruction on the page you linked to for activating the default bucket is to "Enable billing for your project, if you haven't already done so." GCS buckets aren't available until billing is enabled and the API can be activated through the dev console. This is the underlying cause for why the `gcloud` deployment fails on free apps, both on travisCI and locally.

I believe that Google started to auto-provision default GCS buckets for GAE apps that were created within the last 1-2 years or so, which could explain why it may work for you and not for my app (which is a bit older).

**Comment by flowlo** [comment]
Oh, okay, so it seems the problem is more subtle. I might add that that the Apps I mentioned have billing enabled, but often don't generate enough load/traffic to use up the free tier.

For your specific case, there's a tiny chance, that [this](https://stackoverflow.com/questions/28128598) fix might still work. It's about a year old, but maybe still worth giving it a shot (check the link in my answer on SO) ...

Anyway, would you agree on concluding that this issue is unrelated to the deployment provider?

**Comment by erichiggins** [comment]
Ah ha. Looks like that lead me down the right path to resolving the issue.  Here's what I had to do:

Navigate to Project Settings on old console (appengine.google.com) and "Create" Cloud Integration.
After that finished, I had to enable the following APIs on the new console:  
- App Engine Admin API
- Google Cloud Storage
- Google Cloud Storage JSON API


Would it be possible to add some documentation for this provider here to help other folks that may encounter the same issue?

Thanks again for the help!

**Comment by flowlo** [comment]
Cool!

I don't think we should mention Cloud Integration in the README here. The issue with a missing default bucket is *completely unrelated* to any code in this repo and how the provider works. It would be nice to see Google addressing the issue, e.g. by (a) automatically setting up the bucket for old projects upon first deployment or (b) documenting the issue with old projects more prominently.

AFAIK basic functionality of `gcloud` is covered by the App Engine Admin API, which is explicitly mentioned in the README of this repository. Apart from that, one may well need to enable additional APIs depending on their use-case. For example, Compute Engine API and Container Builder API for MVM related stuff. It is not clear to me which APIs are mandatory and useful in any case (i.e. we should suggest to enable them) and which will only rarely be of use.

@ajessup In case you are interested in improving the experience deploying from Travis: Which APIs should someone using `gcloud` activate to get going? Only the App Engine Admin API, or also the Cloud Storage stuff? Is there a mapping that tells which `gcloud` command uses which API? That would be neat ...

**Comment by flowlo** [comment]
Ping @BanzaiMan I think this can be closed.

**Comment by BanzaiMan** [comment]
Thanks! @flowlo
