### ISSUE TITLE
How to change GitHub release title?

### ISSUE THREAD

**Issue by kenorb** [travis-ci/dpl#425]
I've implemented `deploy` according to [docs](https://docs.travis-ci.com/user/deployment/), but my deployments leaving _Release title_ empty:

<img width="466" alt="screen shot 2016-03-31 at 23 41 51" src="https://cloud.githubusercontent.com/assets/266306/14193130/391b1702-f79a-11e5-8c2f-c1deebbbf866.png">

so it fallbacks to the last commit message, which is not very user friendly for people who're visiting release pages:

<img width="910" alt="screen shot 2016-03-31 at 23 42 01" src="https://cloud.githubusercontent.com/assets/266306/14193134/3c24f8d2-f79a-11e5-90af-27cf007c9a3c.png">

Is there any way to apply/override the _Release title_?

**Comment by Joshua-Anderson** [comment]
There isn't any easy way to do this because the message would have to be stored in .travis.yml file, which would require an update before every release. I instead reccomend you create an release from the GitHub UI, which would let you input an message, or create an annotated tag, which also allows you to specify a message

**Comment by berniedurfee-ge** [comment]
If there was an option to specify the release title, I would be able to use TRAVIS_TAG, because I release on tagged releases. This would at least set the title to the tag name, which is common.

It would be nicer then just the last commit message.

**Comment by kenorb** [comment]
I think it's still relevant.

**Comment by kenorb** [comment]
I think it's still relevant.

**Comment by BanzaiMan** [comment]
You can pass `name` to the configuration. If you need a dynamic value to it, you can use environment variables available at the deployment time. 

```yaml
before_deploy:
  - export RELEASE_TITLE=$(date '+%Y%m%d%H%M%S')-$TRAVIS_JOB_NUMBER
deploy:
  provider: releases
  name: $RELEASE_TITLE
  ⋮ # rest
```

**Comment by Setheck** [comment]
I would also like to suggest, as i did in #925 that the name be defaulted to the release tag.

**Comment by BanzaiMan** [comment]
> so it fallbacks to the last commit message
By the way, is this true today? When I deploy without `name`, I see the title is empty, but the release page shows the tag (e.g., https://github.com/BanzaiMan/travis_production_test/releases/tag/test-tag-20181115; if I go to Edit the release, I see that the title is empty.)

**Comment by Setheck** [comment]
I think GitHub does that as a UI nicety. Because if you click Edit, you will see the Title remains unset.
In my case it really just borks the Github Integration because i get a notification with the title ex: `Release - null` but after I set the name field as you suggested in #925 I get what I wanted all along `Release - Tag`

**Comment by BanzaiMan** [comment]
>  if you click Edit, you will see the Title remains unset.

I said this. GitHub shows the tag on the Releases page if the title (set via the `name` parameter) is unset. This is not what @kenorb initially reported, and I wanted the confirmation.

**Comment by Setheck** [comment]
I agree, this is why I thought it was related, but I created a new issue. I wasn't seeing the same behavior
