### ISSUE TITLE
Please support deploy to DigitalOcean

### ISSUE THREAD

**Issue by jingsam** [travis-ci/dpl#435]

**Comment by gabrielcsapo** [comment]
is there a contribution guideline to adding support for this?

**Comment by BanzaiMan** [comment]
What does it mean to "deploy to Digital Ocean"?

**Comment by gabrielcsapo** [comment]
@BanzaiMan They used to have an API that you could use to deploy docker containers too...trying to find it.

**Comment by gabrielcsapo** [comment]
@BanzaiMan seems they have deprecated that API. There is the possibility to push a vagrant box to Digital ocean, they have a tut for it (https://www.digitalocean.com/community/tutorials/how-to-use-digitalocean-as-your-provider-in-vagrant-on-an-ubuntu-12-10-vps)

**Comment by BanzaiMan** [comment]
Unless there is a definite API against which we can implement the feature, I don't think there is much we can do here.

**Comment by waghanza** [comment]
@BanzaiMan I think @gabrielcsapo means a deployment on `Droplets`

It could be a deployment on :

+ a **single** `Droplet`, but it's like a push
+ a *bunch* of `Droplets`, since the _application_ could be behind a *load balancer* => https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-load-balancer

in fact only the second case could only be made throught the *API*, as *AWS CodeDeploy*

**Comment by gdvallance** [comment]
@BanzaiMan I would like to re-open this issue. I would like to use `dpl` via GitLab to deploy applications to DigitalOcean Droplets. There is definitely an API that covers all aspects of a Droplet lifecycles. See: https://developers.digitalocean.com/documentation/v2/
