### ISSUE TITLE
Fine-grained Cache-Control/Expires headers for S3 

### ISSUE THREAD

**Issue by ghost** [travis-ci/dpl#486]
Issue #167 Requests the original feature
PR #170 Added support in for fine-grained cache-control

```
  - provider: s3
    ...
    cache_control:
      - "max-age=300": "*.js"
      - "max-age=3000":
        - "*.css"
        - "*.png"
      - "no-cache"
```

The yml above should set a `cache_control: max-age=[value]` header for JS files to `300`, CSS and PNG files to `3000`, all other files should have a `cache_control: no-cache` header

The result is that all files have their `cache_control` header set to `no-cache`

Either the YML is incorrect, or not being passed down correctly to [dpl/provider/s3](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/s3.rb)

The linter does not validate this as expected:

```
$ travis lint
Warnings for .travis.yml:
[x] in deploy section: dropping cache_control section: unexpected sequence
```

Documentation also needs to be updated
https://docs.travis-ci.com/user/deployment/s3

**Comment by danielwhatmuff** [comment]
Any idea when this will be looked at?

**Comment by hkdobrev** [comment]
@BanzaiMan @Joshua-Anderson @rkh Hi guys, sorry to ping you like that, but since you have reviewed #170, could you please shed some light on what's the status of this? Is it deployed? Does it work and if yes, how? Many thanks!

**Comment by bulyshko** [comment]
It seems [travis-yaml](https://github.com/travis-ci/travis-yaml) was changed since PR #170 was merged into master, because right now yaml parser doesn't expects "cache_control" value to be a "sequence". Will try to investigate how to fix it.

**Comment by BanzaiMan** [comment]
I apologize for this oversight while reviewing the previous PR. It is not clear from the history if it was tested, or ever worked.

The way the data structures in `.travis.yml` translates to the command line flags to `dpl`, which are then passed to the deployment provider code is not very well-documented, and for this, I am sorry. I'll take a look at this S3 feature, as well as better documenting the data flow in the near future.

**Comment by benedikt-budig** [comment]
@BanzaiMan @bulyshko any news on this? Would be great to have that feature working. Many thanks guys!

**Comment by AdamPD** [comment]
Such a necessary feature.  Seems like the work is 95% done but just missing the final touch.

**Comment by bl4ck5un** [comment]
This is indeed a necessary feature.

**Comment by chriselsen** [comment]
I fixed this. Give it a try with the following *.travis.yml* config and please provide feedback
```
deploy:
  - provider: s3
    edge:
      source: chriselsen/dpl
      branch: patch-2
    cache_control: "\"public, max-age=31536000\": *.jpg, *.gif, *.png, *.webp, *.css, *.js, *.ico"
    expires: "\"2030-12-31 00:00:00 -0000\": *.jpg, *.gif, *.png, *.webp, *.css, *.js, *.ico"
```

I know that my config differs from the above example. But to get that example *.travis.yml* config working would require major work in [travis-yml](https://github.com/travis-ci/travis-yml/):
Currently travis-yml passes most of the lines from *.travis.yml* to 'dpl' as string-based key value pairs. It doesn't have the capability to pass an entire YAML substructure. 
Even if we fix this the question would be how 'dpl' should consume it. Because the the *.travis.yml*  setting for e.g. "cache_control: setting" is passed like this to 'dpl':
`dpl --cache_control=setting`
That YAML structure from above would need to be translated into some kind of a string. 
The [s3_spec](https://github.com/travis-ci/dpl/blob/master/spec/provider/s3_spec.rb) provides the following as the spec:
`["max-age=99999999", "no-cache" => ["foo.html", "bar.txt"], "max-age=9999" => "*.txt"]`
That's neither YAML nor JSON, but a string representation of a ruby array of hashes.

And that's one more reason why the previous code would have never worked. Because we would have had to configure this in .travis.yml as
`cache_control: "[\"max-age=99999999\", \"no-cache\" => [\"foo.html\", \"bar.txt\"], \"max-age=9999\" => \"*.txt\"]"`
This would at least pass the value from travis-yml to dpl. But that passed value would now still be a string, not an actual array of hashes. 
But the [s3 provider](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/s3.rb) was expecting this input to be an array of hashes. 

With that here's what I did: 
- Correct the [s3_spec](https://github.com/travis-ci/dpl/pull/958/files#diff-ca754edb5e126306a4d62ec8315e93e8) to represent the test with the actual string `max-age=99999999, no-cache: foo.html, bar.txt, max-age=9999: *.txt"` 
- Correct the [s3_provider](https://github.com/travis-ci/dpl/pull/958/files#diff-0ac612a98b5329ade3dbe91782948452) to parse through the provided string and build an internal hash table. That hash table is then used with [fnmatch](https://apidock.com/ruby/File/fnmatch/class). 

For the above example the hash table would look like this:
```
[*] -> [max-age=99999999]     <--- That's basically the default value
[foo.html] -> [no-cache]
[bar.txt] -> [no-cache]
[*.txt] -> [max-age=9999]
```
Here is an example of a [successful deployment](https://travis-ci.com/edge-cloud/www.edge-cloud.net/builds/101238770) in Travis-CI.

**Comment by svenfuchs** [comment]
I have ported the PR https://github.com/travis-ci/dpl/pull/958 to the new `master` (dpl v2) here with some minor adjustments, mostly making the format more tight: https://github.com/travis-ci/dpl/pull/1062

it would be amazing if some of you could try this out.

I am going to close this issue here. Let's continue the conversation on https://github.com/travis-ci/dpl/pull/1062
