### ISSUE TITLE
upload precompiled wheel to pypi?

### ISSUE THREAD

**Issue by anthrotype** [travis-ci/dpl#496]
I build my manylinux1 wheels using https://github.com/matthew-brett/multibuild and I am trying to use Travis PyPI integration to upload them automatically on tags.

However, at least from the docs, it seems the pypi deployment only accepts predefined `sdist` and `bdist_wheel` options inside `distributions`
https://docs.travis-ci.com/user/deployment/pypi#Uploading-different-distributions

Is there a way to pass `file` options for pypi, i.e. using paths to the precompiled artifacts -- the same way I do with Travis Github Releases deployment?

**Comment by jezdez** [comment]
@anthrotype The PyPI provider is [quite simplistic](https://github.com/travis-ci/dpl/blob/424c7a61c341f184b8aa66df178d4aca31455a6f/lib/dpl/provider/pypi.rb#L96-L97) and doesn't doe much other than running a `setup.py <distributions>` where and then uploads everything from the `dist/` folder.

So assuming you build the wheel files with multibuild, just make sure they end up in `dist/` and leave the `distributions` parameter to `sdist`.

AFAIK the documentation doesn't cover any of the manylinux1 stuff since frankly that's way out of scope of the typical Python package.

**Comment by anthrotype** [comment]
Oh, is that easy? I'll try that, thanks.
