### ISSUE TITLE
S3 deployment apparently succeeds, but no file is present on S3

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/dpl#500]
There is a user report indicating that the deployment to S3 apparently succeeds, but the file is missing.

```
⋮
Fetching: dpl-1.8.17.gem (100%)
Successfully installed dpl-1.8.17
1 gem installed

Installing deploy dependencies
Fetching: jmespath-1.3.1.gem (100%)
Successfully installed jmespath-1.3.1
Fetching: aws-sdk-core-2.4.3.gem (100%)
Successfully installed aws-sdk-core-2.4.3
Fetching: aws-sdk-resources-2.4.3.gem (100%)
Successfully installed aws-sdk-resources-2.4.3
Fetching: aws-sdk-2.4.3.gem (100%)
Successfully installed aws-sdk-2.4.3
4 gems installed
Fetching: mime-types-2.99.2.gem (100%)
Successfully installed mime-types-2.99.2
1 gem installed

Preparing deploy
Logging in with Access Key: ****************WXYZ

Deploying application
uploading "FILE_NAME" with {:content_type=>""}
```

The reporter is deploying to the eu-west-1 region.

We have hitherto not been able to reproduce this problem, and specifying the content type did not affect the outcome of the deployment.

**Comment by aseure** [comment]
Hello, I'm the reporter.

To give you more details about the issue, here's the list of what I've tried so far:
 - Double-checked my AWS credentials and they are OK. I can use them to upload the file (a Go binary) properly using the AWS CLI.
 - Added the `edge: true` to the `deploy` section. The output remains the same and the file is still not uploaded.
 - Tried the `dpl` gem locally on my machine (`1.8.17` on macOS) and got the same output/result as the Travis build (which was `1.8.18.travis.1544.3`)
 - Added a `.sh` extension to my file (which is a Go binary), nothing changed except the value of `content_type` on Travis output which was set to `application/x-sh`.

Here's now what I didn't have the time to try (yet at least):
 - Try the latest debugging build
 - Try to push to another AWS region (currently pushing to `eu-west-1`)
 - 

I'm sure the file exists before the deploy attempt because it's built by the `script` section and `skip_cleanup` is set to `true`. I was asked to try to `ls` the `local_dir` in the `before_deploy` section, the file was there as seen on Travis output.

Thank you to Anna, Hiro, Mathias and Dominic who helped so far on Travis support.

**Comment by Meekohi** [comment]
Having the same issue. Nothing appears at all but there doesn't appear to be an error, which leaves me a little stumped:

```
Preparing deploy
Logging in with Access Key: ****************NTMA

Deploying application
Done. Your build exited with 0.
```

```
deploy:
  - provider: s3
    access_key_id: "[...]"
    secret_access_key:
      secure: "[...]"
    bucket: "mybucket.com"
    skip_cleanup: true
    acl: public_read
    local_dir: www
    detect_encoding: true
    upload_dir: $TRAVIS_BRANCH
    on:
      all_branches: true
```
