### ISSUE TITLE
Submodule files not included in Elastic Beanstalk upload

### ISSUE THREAD

**Issue by jdub** [travis-ci/dpl#592]
Probably worth adding `--recurse-submodules` to the `git ls-files` [invocation](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/elastic_beanstalk.rb#L106).

**Comment by jdub** [comment]
Here's a dirty workaround in the mean time. Won't work if your submodules have the same base path name.

```
- git submodule foreach 'cp -r . /tmp/$(basename $name) && cd $toplevel && git submodule deinit $path && git rm -rf $path && cp -r /tmp/$(basename $name)/ $path/ && git add $path/* $path/.??*'
```

**Comment by jdub** [comment]
This is still an ongoing issue.

**Comment by jdub** [comment]
This is still an ongoing issue.

**Comment by atwalsh** [comment]
Also having this issue.

**Comment by jdub** [comment]
btw, I made PR #593 the day I reported this. 😄

**Comment by BanzaiMan** [comment]
Please test the PR. Thanks.

**Comment by ashenm** [comment]
https://github.com/travis-ci/dpl/pull/593#issuecomment-499462073

**Comment by svenfuchs** [comment]
I believe this issue is addressed in `master` by the way of not using `git ls-files` any more. See now https://github.com/travis-ci/dpl/commit/52032f9a91262284c50f2e4533cc19af4c995e48#diff-ac0853c6afef4a5351a9251c31910ec8

I'm going to close this issue here. Please feel free to re-open if needed, or make a new one.
