### ISSUE TITLE
Deploy triggered by PR ?

### ISSUE THREAD

**Issue by waghanza** [travis-ci/dpl#605]
Hello,

Could `dpl` trigger a **deployment** from a `PR` ?

Regards,

**Comment by Joshua-Anderson** [comment]
Not right now, because dpl requires secure environmental variables not available in pull requests.

**Comment by waghanza** [comment]
even with `$TRAVIS_PULL_REQUEST` variable ?

**Comment by Joshua-Anderson** [comment]
@waghanza Yes. Because anyone can open a pull request, nothing sensitive can be in them. To send secure info like API keys to dpl, travis uses environmental variables. Therefore, pull requests cannot trigger deployments because anybody could trivially steal secret information from the environmental variables.

**Comment by BanzaiMan** [comment]
As documented: https://docs.travis-ci.com/user/deployment/#Pull-Requests

I'm closing this now.

**Comment by waghanza** [comment]
@Joshua-Anderson unserstood, a branch update event show be accurate. thanks
