### ISSUE TITLE
OSX s3 deploy stopped working: `rescue in deploy': uninitialized constant Aws (NameError)

### ISSUE THREAD

**Issue by orktes** [travis-ci/dpl#685]
Issues seem to have started with `dpl-1.8.41` as last successful was with `dpl-1.8.40`.

```sh
Deploying application
uploading "somefile" with {:content_type=>"", :acl=>"public-read"}
/Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.41/lib/dpl/provider/s3.rb:76:in `rescue in deploy': uninitialized constant Aws (NameError)
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.41/lib/dpl/provider/s3.rb:75:in `deploy'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.41/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.41/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.41/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `<main>'
failed to deploy
```

```sh
os: osx
osx_image: xcode8.2
```

Issue might be related to the fact osx containers have pre-installed version of `aws-sdk@1.66.0` that matches the new version range `'< 3.0'` but is too old otherwise.

```sh
$ gem list aws-sdk
*** LOCAL GEMS ***
aws-sdk (1.66.0)
aws-sdk-v1 (1.66.0)
```

**Comment by BanzaiMan** [comment]
Sorry for the troubles. We're taking a look now.

**Comment by BanzaiMan** [comment]
Thanks for reporting the issue. Indeed, the issue arises from the lax requirement for `aws-sdk` gem in our 1.8.41 release.

I've pushed an experimental fix, available with the following:

```yaml
deploy:
  provider: s3
  edge:
    branch: mac-aws
    ⋮ # rest
```

Please test this. With a few reports of success, I'll release 1.8.42.

The issue is confined to cases where an older version of `aws-sdk` exists. If you install a Ruby runtime, for example, this would not manifest.

It is not yet clear to me yet what requirement is installing this, but switching to `~> 2.0` should force installation of some `2.x` (my experiment shows 2.10.36), which should be good.

**Comment by orktes** [comment]
Thanks for the fix. Seems to work now (first build deployed correctly). Will report back with further results.

**Comment by orktes** [comment]
Second one finished successfully.

**Comment by BanzaiMan** [comment]
Great!
