### ISSUE TITLE
[provider: pypi] drop docs uploading code

### ISSUE THREAD

**Issue by webknjaz** [travis-ci/dpl#835]
pythonhosted has been deprecated and new uploads there don't work anyway.

**Comment by webknjaz** [comment]
It looks like [devpi supports hosting documentation](https://devpi.net/docs/devpi/devpi/stable/%2Bd/index.html), so that argument might still be useful for custom PYPI URLs, while for Warehouse it must print out some warning.

**Comment by svenfuchs** [comment]
I have renamed the option `--skip_upload_docs` to just `--upload_docs` to make it more clear that not uploading docs is the default. I have also changed the wording on the `note` on the option (which is going to automatically end up in the README)

Do you all think this is good enough?

I am going to close this issue here. Please feel free to reopen if needed.

**Comment by webknjaz** [comment]
Sounds good.

**Comment by svenfuchs** [comment]
whoops. i should have added the PR i was referencing https://github.com/travis-ci/dpl/pull/1066 😆
