### ISSUE TITLE
Support for lambdas using layers

### ISSUE THREAD

**Issue by jrupp** [travis-ci/dpl#933]
https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-using

AWS Announced "Layers" for the Lambda service.  Please add the ability to specify layers that a lambda function needs to use.

**Comment by tdmalone** [comment]
unstale

**Comment by paulbailey** [comment]
Yes, Lambda Layer support would be great, both specifying layers for a function to use, and for deploying the layers themselves.

**Comment by jrupp** [comment]
I had not originally considered for deploying the layers, but that has come up more and more on my end.. so having a way to deploy them with travis-ci would also be great

**Comment by tdmalone** [comment]
unstale

**Comment by svenfuchs** [comment]
I have added an option `--layers` here: https://github.com/travis-ci/dpl/pull/1070, which I believe should implement this feature. However, I am not super familiar with using Lambda, so I'm not sure if something is lacking. If so, please let me know on the PR.

@jrupp @tdmalone @paulbailey it would be amazing if one of you could try this out.

I am going to close this issue here. Please feel free to re-open if needed.
