### ISSUE TITLE
Support for Google App Engine (GAE) deployment 

### ISSUE THREAD

**Issue by jeanEpek** [travis-ci/dpl#94]
We would like to add Google App Engine (GAE) as a supported provider in the deploy section.

We currently use an after_success section but it's not ideal.

**Comment by Trii** [comment]
Using the gcloud tool you can deploy any app regardless of language. It also supports service accounts for auth via `gcloud auth activate-service-account` passing a json key file instead of having to use a user's refresh token.

This is how I implement it:

```
install:
  - if [[ ! -f google-cloud-sdk/path.bash.inc ]]; then
      echo "Downloading google cloud sdk";
      wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip;
      unzip -qq google-cloud-sdk.zip;
      google-cloud-sdk/install.sh --usage-reporting false --path-update false --rc-path=~/.bashrc --bash-completion false --override-components=app;
    fi;
  - google-cloud-sdk/bin/gcloud components update preview app --quiet

.... snip

after_success:
- ./travis-ci-deploy.sh
```

Where **travis-ci-deploy.sh* boils down to the following:
```
google-cloud-sdk/bin/gcloud auth activate-service-account \
    --key-file "${GAE_CLIENT_KEY_JSON_FILE}"
google-cloud-sdk/bin/gcloud \
    --project "${GAE_PROJECT_ID}" \
    preview app deploy \
    --version "${GAE_VERSION_LABEL}" \
    --quiet \
    "app.yaml"
```

[gcloud preview app deploy](https://cloud.google.com/sdk/gcloud/reference/preview/app/deploy) reference.

**Comment by flowlo** [comment]
Hi!

I'm using an [`after_success`](https://github.com/coduno/app/blob/master/.travis.yml) similar to @Trii and would love to help improving support for GAE.

Disclaimer: I only use GAE for Go and a bit of Python, also I mainly use managed VMs. The other stuff I do not know very well.

As it seems to me there was a little confusion about Google's tools for GAE. Let me add my portion to this confusion: There is [`appcfg`](https://cloud.google.com/appengine/docs/appcfg) (also `appcfg.py`) which is old (AFAIK) and language agnostic. It is wrapped by other tools (such as `goapp`). I might even suspect that it will fade some day. Different language runtimes have added their flavours to it.

Also, there is the [`gcloud`](https://cloud.google.com/sdk/gcloud/) which is not only relevant for GAE but also GCE (they are both part of "Google Cloud"). This is the tool I mostly use for administrating App Engine. It also wraps `appcfg` and friends with it's [`gcloud preview app ...`](https://cloud.google.com/sdk/gcloud/reference/preview/app/) commands. If you read closely, that page says:

> These commands replace their equivalents in the appcfg tool.

Hmm ... This is why I suggest dropping `appcfg` altogether and adopting `gcloud preview app`. As the GAE provider is in some non-stable state anyway, this sounds reasonable. Also, I found that Google is quite responsive over at their [issue tracker](https://code.google.com/p/google-cloud-sdk/issues/list) (way more than they normally are, at least), and we might be able to influence the tooling a bit.

I'd be happy to write up a provider that takes something like the Application ID, location of the JSON secret (with reasonable default), module, version ... and whatever comes to my mind.

Also, a note on Managed VMs on GAE (the thingy I am using): They require a Docker host to prepare the container for deployment. We would probably have to wait for [this to happen](https://twitter.com/travisci/status/628789476756713472).

**Comment by flowlo** [comment]
Hi!

I'm using an [`after_success`](https://github.com/coduno/app/blob/master/.travis.yml) similar to @Trii and would love to help improving support for GAE.

Disclaimer: I only use GAE for Go and a bit of Python, also I mainly use managed VMs. The other stuff I do not know very well.

As it seems to me there was a little confusion about Google's tools for GAE. Let me add my portion to this confusion: There is [`appcfg`](https://cloud.google.com/appengine/docs/appcfg) (also `appcfg.py`) which is old (AFAIK) and language agnostic. It is wrapped by other tools (such as `goapp`). I might even suspect that it will fade some day. Different language runtimes have added their flavours to it.

Also, there is the [`gcloud`](https://cloud.google.com/sdk/gcloud/) which is not only relevant for GAE but also GCE (they are both part of "Google Cloud"). This is the tool I mostly use for administrating App Engine. It also wraps `appcfg` and friends with it's [`gcloud preview app ...`](https://cloud.google.com/sdk/gcloud/reference/preview/app/) commands. If you read closely, that page says:

> These commands replace their equivalents in the appcfg tool.

Hmm ... This is why I suggest dropping `appcfg` altogether and adopting `gcloud preview app`. As the GAE provider is in some non-stable state anyway, this sounds reasonable. Also, I found that Google is quite responsive over at their [issue tracker](https://code.google.com/p/google-cloud-sdk/issues/list) (way more than they normally are, at least), and we might be able to influence the tooling a bit.

I'd be happy to write up a provider that takes something like the Application ID, location of the JSON secret (with reasonable default), module, version ... and whatever comes to my mind. Other CI Providers require you to give away your personal credentials by the way: [Circle CI](https://circleci.com/docs/deploy-google-app-engine), [Shippable](http://docs.shippable.com/appengine/), [Codeship (at least via OAuth)](https://codeship.com/documentation/continuous-deployment/deployment-to-google-app-engine/). That makes me sad, I think Service Accounts are *made* for CI, and Travis should support that.

Also, a note on Managed VMs on GAE (the thingy I am using): They require a Docker host to prepare the container for deployment. We would probably have to wait for [this to happen](https://twitter.com/travisci/status/628789476756713472).

Off topic: I think getting in touch with `gcloud` might even be valuable thinking towards a GCE provider.

BTW, this issue is missing [proper labeling](https://github.com/travis-ci/dpl/labels/provider%3A%20gae%20%28Google%20App%20Engine%29).

**Comment by Trii** [comment]
FWIW this is how I do it now https://github.com/Trii/appengine-buildout-template/blob/master/travis-ci-deploy.sh

**Comment by flowlo** [comment]
Just found [this](https://groups.google.com/d/msg/app-engine-managed-vms/3ygjc7dPGi8/StqF0qCzFIsJ) post by a [Andrew Jessup](https://plus.google.com/+AndrewJessup/about) to app-engine-managed-vms@googlegroups.com (restricted), from 2015-07-08 that support the rumors:

> Hi folks,
> 
> We're making an important change to the Google Cloud SDK to simplify how
App Engine developers can access and work with the SDK.
> 
> As of the next release, 0.9.68, of the Google Cloud SDK - we will no longer
be distributing the stand alone App Engine SDKs.
> 
> The gcloud preview app deploy and gcloud preview app run commands that most
developers use within gcloud will continue to work, users should not notice
any obvious change.
> 
> For users who were directly using appcfg.py, appcfg.sh, dev_appserver.py or
dev_appserver.sh scripts, or the GUI launchers that were bundled with the
Google Cloud SDK, you have two options:
> 
> You can continue to use the latest versions of these tools used by
installing them from the stand-alone App Engine SDKs that can be found
here: https://cloud.google.com/appengine/downloads.
> 
> In the short term, if you need to prevent this from happening, you can pin
a version of gcloud SDK with the following commands:
> 
>   `gcloud config set --scope=installation component_manager/fixed_sdk_version 0.9.67`
>   `gcloud components update`
> 
> As part of this change, the gae-java, gae-python, gae-php, and gae-go
components no longer exist in the component manager.  The `gcloud preview
app run` command will install language specific runtime libraries on
demand, as needed by your application.
> 
> If you have questions or concerns, please let us know.

> Thanks,

> Andrew, on behalf of the Cloud SDK team


> Andrew Jessup | Product Manager, Google Cloud Platform | jes...@google.com

**Comment by Trii** [comment]
I spoke with some people in the #gcloud channel on freenode and they said that this does not affect using gcloud for deployment. It just means that you have to download the google app engine sdk in order to run your app locally since they will no longer bundle tools like `dev_appserver.py` and `appcfg.py`

**Comment by flowlo** [comment]
Yeah, but I see that all these steps as a plan to deprecate `dev_appserver.py` and `appcfg.py` in the long term. And even if it's not true it still means that a dpl provider should use `gcloud` for deployment.

**Comment by ajessup** [comment]
Hey folks - `gcloud app` is definitely the right way forward here for GAE and GCE. It is a single toolchain that supports multiple languages and deployment targets, including Managed VMs. `gcloud app run` is effectively bundling the `dev_appserver.py` process and `gcloud app deploy` is a fork of `appcfg.py`. We'll hope to be removing the `preview` label fairly shortly.

I work pretty closely with the gcloud team and would be happy to facilitate a Travis integration. Drop me a line at `jessup AT google.com` and let me know what you need.

**Comment by waprin** [comment]
@flowlo Managed VMs no longer require Docker to deploy, currently the default tries to use Docker locally but falls back to a remote Docker deploy (using a GCE instance). Soon the remote Docker deploy will be the default. Until then if you want to avoid the fallback behavior, you can force it to use the remote Docker deploy with --docker-build=remote .

**Comment by waprin** [comment]
Here is an example of a deploy to Managed VMs from Travis: 

https://github.com/GoogleCloudPlatform/continuous-deployment-demo/blob/managed_vms/.travis.yml

Note the line

`ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine`

which generates keys to copy to the remote GCE instance to do the Docker build. Otherwise it's similar to the other App Engine examples like the one Trii posted. Would love to see this builtin to Travis though.

**Comment by BanzaiMan** [comment]
GAE provider now uses `gcloud`. Can this issue be closed?

**Comment by BanzaiMan** [comment]
Closing this.

**Comment by aubm** [comment]
For the record, deployment to GAE is not working for my Go app, this definitely has something to do with those issues:

- https://code.google.com/p/googleappengine/issues/detail?id=13199
- https://groups.google.com/forum/#!topic/google-appengine-go/eoSSKKN_VmI
- https://groups.google.com/forum/#!topic/google-cloud-sdk/x8Rf9n_U55M
- https://code.google.com/p/googleappengine/issues/detail?id=12554

**Comment by flowlo** [comment]
@aubm please check whether #498 is the issue you are experiencing and maybe comment about your situation there and/or upvote it. If not, please file a new issue with a more complete description so that I can take a detailed look. Thank you very much!
